name: manual_trigger_workflow

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
        - cron: '0 5 * * 1-5'

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name:  Checkout code
          run: echo "manual trigger workflow"